// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggyrgwlqeiufnlkdwqud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneXJnd2xxZWl1Zm5sa2R3cXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTkyODAsImV4cCI6MjA1OTc5NTI4MH0.8AlxnvW_x-5a46RlruNaxrZyVaVBVkSr90zclSyFK1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);